server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

#配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #mybatisPlus配置逻辑删除
  global-config:
    db-config:
      logic-delete-value: 1  #配置逻辑删除字段为1是删除
      logic-not-delete-value: 0  #配置逻辑删除字段为0是未删除